=== laplumadedumbo/thothweb/RichTextEditor/i18N.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="i18N" elementFormDefault="qualified" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="i18N">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Languages" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Language" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Fonts" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Font" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                              </xs:sequence>
                              <xs:attribute name="Name" type="xs:string" />
                              <xs:attribute name="Description" type="xs:string" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Messages" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Message" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                              </xs:sequence>
                              <xs:attribute name="Id" type="xs:string" />
                              <xs:attribute name="Msgstring" type="xs:string" />
                              <xs:attribute name="Group" type="xs:string" use="optional" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="code" type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== laplumadedumbo/thothweb/trunk/RichTextEditor/i18N.xml
<?xml version="1.0" encoding="utf-8"?>
<i18N xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation='i18N.xsd'>
  <Languages>
    <Language code='en-us'>
      <Fonts>
        <Font Name='Arial' Description='Arial' />
        <Font Name='Courier' Description='Courier' />
        <Font Name='Tahoma' Description='Tahoma' />
        <Font Name='Times New Roman' Description='Times New Roman' />
        <Font Name='Verdana' Description='Verdana' />
      </Fonts>
      <Messages>
        <Message Id="1" Msgstring="Please use CTRL+C for copy, CTRL+X for cut, and CTRL+V for paste" />
        <Message Id="2" Msgstring="To create a new code block, please enter your code in the post editor below, highlight it, and select the “Code Block” button."/>
        <Message Id="CodeBlock" Msgstring="Code Block"/>
        <Message Id="Cut" Group="ToolTip" Msgstring="Cut"/>
        <Message Id="Paste" Group="ToolTip" Msgstring="Paste"/>
        <Message Id="Copy" Group="ToolTip" Msgstring="Copy"/>
        <Message Id="Bold" Group="ToolTip" Msgstring="Bold"/>
        <Message Id="Italics" Group="ToolTip" Msgstring="Italics"/>
        <Message Id="Underline" Group="ToolTip" Msgstring="Underline"/>
        <Message Id="Indent" Group="ToolTip" Msgstring="Increase Indent"/>
        <Message Id="Outdent" Group="ToolTip" Msgstring="Decrease Indent"/>
        <Message Id="LeftJustify" Group="ToolTip" Msgstring="Left Justify"/>
        <Message Id="CenterJustify" Group="ToolTip" Msgstring="Center Justify"/>
        <Message Id="RightJustify" Group="ToolTip" Msgstring="Right Justify"/>
        <Message Id="BulletedList" Group="ToolTip" Msgstring="Bulleted List"/>
        <Message Id="NumberedList" Group="ToolTip" Msgstring="Numbered List"/>
        <Message Id="Hyperlink" Group="ToolTip" Msgstring="Insert Hyperlink"/>
        <Message Id="MCodeBlock" Group="ToolTip" Msgstring="Code Block"/>
        <Message Id="FgColor" Group="ToolTip" Msgstring="Text Color"/>
        <Message Id="BgColor" Group="ToolTip" Msgstring="Background Color"/>
        <Message Id="Emoticons" Group="ToolTip" Msgstring="Emoticons"/>
      </Messages>
    </Language>
    <Language code='cs-cz'>
      <Fonts>
        <Font Name='Arial' Description='Arial' />
        <Font Name='Courier' Description='Courier' />
        <Font Name='Tahoma' Description='Tahoma' />
        <Font Name='Times New Roman' Description='Times New Roman' />
        <Font Name='Verdana' Description='Verdana' />
      </Fonts>
      <Messages>
        <Message Id="1" Msgstring="Pro zkopírování použijte kombinaci kláves CTRL+C, pro vyjmutí kombinaci CTRL+X a pro vložení kombinaci CTRL+V." />
        <Message Id="2" Msgstring="To create a new code block, please enter your code in the post editor below, highlight it, and select the “Code Block” button."/>
        <Message Id="CodeBlock" Msgstring="Blok kódu"/>
        <Message Id="Cut" Group="ToolTip" Msgstring="Vyjmout"/>
        <Message Id="Paste" Group="ToolTip" Msgstring="Vložit"/>
        <Message Id="Copy" Group="ToolTip" Msgstring="Kopírovat"/>
        <Message Id="Bold" Group="ToolTip" Msgstring="Tučné"/>
        <Message Id="Italics" Group="ToolTip" Msgstring="Kurzíva"/>
        <Message Id="Underline" Group="ToolTip" Msgstring="Podtrhnout"/>
        <Message Id="Indent" Group="ToolTip" Msgstring="Zvětšit odsazení"/>
        <Message Id="Outdent" Group="ToolTip" Msgstring="Zmenšit odsazení"/>
        <Message Id="LeftJustify" Group="ToolTip" Msgstring="Zarovnat vlevo"/>
        <Message Id="CenterJustify" Group="ToolTip" Msgstring="Center Justify"/>
        <Message Id="RightJustify" Group="ToolTip" Msgstring="Zarovnat vpravo"/>
        <Message Id="BulletedList" Group="ToolTip" Msgstring="Odrážky"/>
        <Message Id="NumberedList" Group="ToolTip" Msgstring="Číslování"/>
        <Message Id="Hyperlink" Group="ToolTip" Msgstring="Hypertextový odkaz"/>
        <Message Id="MCodeBlock" Group="ToolTip" Msgstring="Code Block"/>
        <Message Id="FgColor" Group="ToolTip" Msgstring="Barva popředí"/>
        <Message Id="BgColor" Group="ToolTip" Msgstring="Barva pozadí"/>
        <Message Id="Emoticons" Group="ToolTip" Msgstring="Emotikona"/>
      </Messages>
    </Language>
    <Language code='es-es'>
      <Fonts>
        <Font Name='Arial' Description='Arial' />
        <Font Name='Courier' Description='Courier' />
        <Font Name='Tahoma' Description='Tahoma' />
        <Font Name='Times New Roman' Description='Times New Roman' />
        <Font Name='Verdana' Description='Verdana' />
      </Fonts>
      <Messages>
        <Message Id="1" Msgstring="Use CTRL+C para copiar, CTRL+X para cortar y CTRL+V para pegar" />
        <Message Id="2" Msgstring="Para crear un bloque de código nuevo, escriba su código en el editor que aparece a continuación, resáltelo y seleccione el botón &quot;Bloque de código&quot;."/>
        <Message Id="CodeBlock" Msgstring="Bloque de código"/>
        <Message Id="Cut" Group="ToolTip" Msgstring="Cortar texto"/>
        <Message Id="Paste" Group="ToolTip" Msgstring="Pegar texto"/>
        <Message Id="Copy" Group="ToolTip" Msgstring="Copiar texto"/>
        <Message Id="Bold" Group="ToolTip" Msgstring="Negrita"/>
        <Message Id="Italics" Group="ToolTip" Msgstring="Cursiva"/>
        <Message Id="Underline" Group="ToolTip" Msgstring="Subrayado"/>
        <Message Id="Indent" Group="ToolTip" Msgstring="Aumentar sangr&amp;iacute;a"/>
        <Message Id="Outdent" Group="ToolTip" Msgstring="Reducir sangr&amp;iacute;a"/>
        <Message Id="LeftJustify" Group="ToolTip" Msgstring="Alinear a la izquierda"/>
        <Message Id="CenterJustify" Group="ToolTip" Msgstring="Alinear al centro"/>
        <Message Id="RightJustify" Group="ToolTip" Msgstring="Alinear a la derecha"/>
        <Message Id="BulletedList" Group="ToolTip" Msgstring="Lista con vi&amp;ntilde;etas"/>
        <Message Id="NumberedList" Group="ToolTip" Msgstring="Lista numerada"/>
        <Message Id="Hyperlink" Group="ToolTip" Msgstring="Insertar v&amp;iacute;nculo"/>
        <Message Id="MCodeBlock" Group="ToolTip" Msgstring="Bloque de código"/>
        <Message Id="FgColor" Group="ToolTip" Msgstring="Color de texto"/>
        <Message Id="BgColor" Group="ToolTip" Msgstring="Color de fondo"/>
        <Message Id="Emoticons" Group="ToolTip" Msgstring="Iconos gestuales"/>
      </Messages>
    </Language>
    <Language code='de-de'>
      <Fonts>
        <Font Name='Arial' Description='Arial' />
        <Font Name='Courier' Description='Courier' />
        <Font Name='Tahoma' Description='Tahoma' />
        <Font Name='Times New Roman' Description='Times New Roman' />
        <Font Name='Verdana' Description='Verdana' />
      </Fonts>
      <Messages>
        <Message Id="1" Msgstring="Drücken Sie STRG+C zum Kopieren, STRG+X zum Ausschneiden und STRG+V zum Einfügen" />
        <Message Id="2" Msgstring="Um einen neuen Abschnitt mit Quellcode zu erstellen, geben Sie bitte zuerst den Code im Beitragseditor ein, markieren ihn, und klicken dann auf die „Quellcodeabschnitt“ Schaltfläche."/>
        <Message Id="CodeBlock" Msgstring="Quellcodeabschnitt"/>
        <Message Id="Cut" Group="ToolTip" Msgstring="Text ausschneiden"/>
        <Message Id="Paste" Group="ToolTip" Msgstring="Text einf&amp;uuml;gen"/>
        <Message Id="Copy" Group="ToolTip" Msgstring="Text kopieren"/>
        <Message Id="Bold" Group="ToolTip" Msgstring="Fett"/>
        <Message Id="Italics" Group="ToolTip" Msgstring="Kursiv"/>
        <Message Id="Underline" Group="ToolTip" Msgstring="Unterstrichen"/>
        <Message Id="Indent" Group="ToolTip" Msgstring="Einzug vergr&amp;ouml;&amp;szlig;ern"/>
        <Message Id="Outdent" Group="ToolTip" Msgstring="Einzug verkleinern"/>
        <Message Id="LeftJustify" Group="ToolTip" Msgstring="Linksb&amp;uuml;ndig"/>
        <Message Id="CenterJustify" Group="ToolTip" Msgstring="Zentriert"/>
        <Message Id="RightJustify" Group="ToolTip" Msgstring="Rechtsb&amp;uuml;ndig"/>
        <Message Id="BulletedList" Group="ToolTip" Msgstring="Aufz&amp;auml;hlung"/>
        <Message Id="NumberedList" Group="ToolTip" Msgstring="Nummerierung"/>
        <Message Id="Hyperlink" Group="ToolTip" Msgstring="Link einf&amp;uuml;gen"/>
        <Message Id="MCodeBlock" Group="ToolTip" Msgstring="Quellcodeabschnitt"/>
        <Message Id="FgColor" Group="ToolTip" Msgstring="Textfarbe"/>
        <Message Id="BgColor" Group="ToolTip" Msgstring="Hintergrundfarbe"/>
        <Message Id="Emoticons" Group="ToolTip" Msgstring="Emoticons"/>
      </Messages>
    </Language>
    <Language code='fr-fr'>
      <Fonts>
        <Font Name='Arial' Description='Arial' />
        <Font Name='Courier' Description='Courier' />
        <Font Name='Tahoma' Description='Tahoma' />
        <Font Name='Times New Roman' Description='Times New Roman' />
        <Font Name='Verdana' Description='Verdana' />
      </Fonts>
      <Messages>
        <Message Id="1" Msgstring="Utilisez la commande CTRL+C pour copier du texte, CTRL+X pour couper et CTRL+V pour coller." />
        <Message Id="2" Msgstring="Pour créer un nouvel extrait de code, veuillez entrer votre code dans l’éditeur de message ci-dessous, selectionez-le, et cliquez sur le bouton « Extrait de code »."/>
        <Message Id="CodeBlock" Msgstring="Extrait de code"/>
        <Message Id="Cut" Group="ToolTip" Msgstring="Couper"/>
        <Message Id="Paste" Group="ToolTip" Msgstring="Coller"/>
        <Message Id="Copy" Group="ToolTip" Msgstring="Copier"/>
        <Message Id="Bold" Group="ToolTip" Msgstring="Gras"/>
        <Message Id="Italics" Group="ToolTip" Msgstring="Italique"/>
        <Message Id="Underline" Group="ToolTip" Msgstring="Soulign&amp;eacute;"/>
